
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
//import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class CustomerCheckIn extends javax.swing.JFrame {

    
    /**
     * Creates new form CustomerCheckIn
     */
    public CustomerCheckIn() {
        initComponents();
         SimpleDateFormat  dat=new SimpleDateFormat("yyyy/MM/dd ");
         Date d=new Date();
         txtdate.setText(dat.format(d));
         txtname.requestFocus();
         
         
        PreparedStatement pst;
        
        ResultSet rs;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","ketan9535");
            //st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            pst=con.prepareStatement("select roomnumber from room where status=? AND roomtype=? AND bed=?");
            pst.setString(1,"Not Booked");
            pst.setString(2, comboroomtype.getItemAt(comboroomtype.getSelectedIndex()));
            pst.setString(3, combobed.getItemAt(combobed.getSelectedIndex()));
            rs=pst.executeQuery();
            while(rs.next()){
                comboroomnumber.addItem(rs.getString("roomnumber"));
            }
            pst=con.prepareStatement("select price from room where roomnumber=?");
            pst.setString(1,comboroomnumber.getItemAt(comboroomnumber.getSelectedIndex()));
            rs=pst.executeQuery();
            if(rs.next())
            txtprice.setText(rs.getString("price"));
        }catch(ClassNotFoundException | SQLException e){
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtmob = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        combogender = new javax.swing.JComboBox<>();
        txtnat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        combobed = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        comboroomtype = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        comboroomnumber = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblemail = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtaddress1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 380, 35));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("Mobile Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 291, 30));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 380, 37));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 380, 40));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setText("Nationality");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 390, 40));

        txtname.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnameFocusLost(evt);
            }
        });
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 390, 42));

        txtmob.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtmob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmobFocusLost(evt);
            }
        });
        txtmob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmobActionPerformed(evt);
            }
        });
        txtmob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmobKeyPressed(evt);
            }
        });
        getContentPane().add(txtmob, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 390, 40));

        txtemail.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemailFocusLost(evt);
            }
        });
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtemailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtemailKeyTyped(evt);
            }
        });
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 390, 40));

        combogender.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        combogender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        combogender.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                combogenderFocusLost(evt);
            }
        });
        combogender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combogenderActionPerformed(evt);
            }
        });
        combogender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                combogenderKeyPressed(evt);
            }
        });
        getContentPane().add(combogender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 390, 50));

        txtnat.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtnat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnatFocusLost(evt);
            }
        });
        txtnat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnatActionPerformed(evt);
            }
        });
        txtnat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnatKeyPressed(evt);
            }
        });
        getContentPane().add(txtnat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 390, 40));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setText("Id Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 294, 30));

        txtid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtidFocusLost(evt);
            }
        });
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidKeyPressed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 670, 390, 40));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel9.setText("Check IN Date(Today)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 294, 50));

        txtdate.setEditable(false);
        txtdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 138, 350, 40));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel10.setText("Bed Type");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 257, 40));

        combobed.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        combobed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double" }));
        combobed.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combobedItemStateChanged(evt);
            }
        });
        combobed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobedActionPerformed(evt);
            }
        });
        getContentPane().add(combobed, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 350, 40));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel11.setText("Room Type");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 257, 50));

        comboroomtype.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboroomtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "NON AC", "Premium" }));
        comboroomtype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboroomtypeItemStateChanged(evt);
            }
        });
        comboroomtype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboroomtypeMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                comboroomtypeMouseReleased(evt);
            }
        });
        comboroomtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboroomtypeActionPerformed(evt);
            }
        });
        getContentPane().add(comboroomtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 350, 40));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel12.setText("Room Number");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 340, 40));

        comboroomnumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboroomnumber.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboroomnumberItemStateChanged(evt);
            }
        });
        comboroomnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboroomnumberActionPerformed(evt);
            }
        });
        getContentPane().add(comboroomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, 350, 40));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel13.setText("Price");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 350, 30));

        txtprice.setEditable(false);
        txtprice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 509, 350, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, 40, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Check in now");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 640, 170, 40));

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 640, 90, 40));

        lblemail.setForeground(new java.awt.Color(204, 0, 0));
        lblemail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 390, 20));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 294, 30));

        txtaddress1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtaddress1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtaddress1FocusLost(evt);
            }
        });
        txtaddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddress1ActionPerformed(evt);
            }
        });
        txtaddress1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtaddress1KeyPressed(evt);
            }
        });
        getContentPane().add(txtaddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 390, 40));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Customer Check In");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
txtname.setText("");
txtmob.setText("");
txtemail.setText("");
txtnat.setText("");
txtid.setText("");
combogender.setSelectedIndex(0);
combobed.setSelectedIndex(0);
comboroomtype.setSelectedIndex(0);
if(comboroomnumber.getItemCount()==0)
    txtprice.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed

    }//GEN-LAST:event_txtdateActionPerformed

    private void comboroomnumberItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboroomnumberItemStateChanged
            PreparedStatement pst;
            ResultSet rs;
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","ketan9535");
            pst=con.prepareStatement("select price from room where roomnumber=?");
            pst.setString(1,comboroomnumber.getItemAt(comboroomnumber.getSelectedIndex()));
            rs=pst.executeQuery();
            if(rs.next())
            txtprice.setText(rs.getString("price"));       
            }catch(ClassNotFoundException | SQLException e){
        }
        
    }//GEN-LAST:event_comboroomnumberItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    if(txtname.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Name should not be empty");
      txtname.requestFocus();
    }
    else if(txtmob.getText().equals("")){
       JOptionPane.showMessageDialog(this, "Mobile number should not be empty");
       txtmob.requestFocus();
    }
    else if(txtemail.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Email should not be empty");
      txtemail.requestFocus();
    }
    else if(txtnat.getText().equals("")){
       JOptionPane.showMessageDialog(this, "Nationality should not be empty");
       txtnat.requestFocus();
    }
    else if(txtaddress1.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Address should not be empty");
      txtaddress1.requestFocus();
    }
    else if(txtid.getText().equals("")){
      JOptionPane.showMessageDialog(this, "Id should not be empty");
      txtid.requestFocus();
    }
    else if(txtprice.getText().equals("")){
       JOptionPane.showMessageDialog(this, "Sorry, This type of Room Not available Select another room ");
       txtprice.requestFocus();
    }
    else if(txtmob.getText().length()!=10){
        JOptionPane.showMessageDialog(this, "Mobile Number Should be 10 Digit.");
    }
    
    else{
        
        
        System.out.println("outside try block");
        try {
            long l=Long.parseLong(txtmob.getText());
        l=Long.parseLong(txtid.getText());
        Connection con=null;
            PreparedStatement pst;
            ResultSet rs;
            System.out.println("before class forname");
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","ketan9535");
            System.out.println("before query");
            
            pst=con.prepareStatement("insert into customer(name,mobile,email,gender,address,id,nationality,joindate,roomnumber,bed,roomtype,price,status)values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, txtname.getText());
            pst.setString(2, txtmob.getText());
            pst.setString(3, txtemail.getText().toLowerCase());
            pst.setString(4, combogender.getItemAt(combogender.getSelectedIndex()));
            pst.setString(5, txtaddress1.getText());
            pst.setString(6, txtid.getText()); 
            pst.setString(7, txtnat.getText());
            pst.setString(8, txtdate.getText());
            pst.setString(9, (String) comboroomnumber.getSelectedItem());
            pst.setString(10, combobed.getItemAt(combobed.getSelectedIndex()));
            pst.setString(11, (String) comboroomtype.getSelectedItem());
            pst.setString(12, txtprice.getText());
            pst.setString(13,"NULL");
         
            pst.executeUpdate();
            System.out.println("after query");
            JOptionPane.showMessageDialog(this, "Customer checked In");
            pst=con.prepareStatement("update room set status=? where roomnumber=?");
            pst.setString(1,"Booked" );
            pst.setString(2, (String) comboroomnumber.getSelectedItem());
            pst.executeUpdate();
            pst=con.prepareStatement("select roomnumber from room where status=? AND roomtype=? AND bed=?");
            pst.setString(1,"Not Booked");
            pst.setString(2, comboroomtype.getItemAt(comboroomtype.getSelectedIndex()));
            pst.setString(3, combobed.getItemAt(combobed.getSelectedIndex()));
            rs=pst.executeQuery();
            comboroomnumber.removeAllItems();
            while(rs.next()){
                comboroomnumber.addItem(rs.getString("roomnumber"));
            }
            pst=con.prepareStatement("select price from room where roomnumber=?");
            pst.setString(1,comboroomnumber.getItemAt(comboroomnumber.getSelectedIndex()));
            rs=pst.executeQuery();
            if(rs.next()){
            txtprice.setText(rs.getString("price"));
            }
            txtname.setText("");
            txtmob.setText("");
            txtnat.setText("");
            txtemail.setText("");
            txtid.setText("");
            txtaddress1.setText("");
            combogender.setSelectedIndex(0);
            combobed.setSelectedIndex(0);
            comboroomtype.setSelectedIndex(0);
            if(comboroomnumber.getItemCount()==0)
                txtprice.setText("");
            }catch(HeadlessException | ClassNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(this," Unable to connect to database");
            }
    }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboroomtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboroomtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboroomtypeActionPerformed

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseReleased

    private void comboroomtypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboroomtypeItemStateChanged
        PreparedStatement pst;
        ResultSet rs;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","ketan9535");
            pst=con.prepareStatement("select roomnumber from room where status=? AND roomtype=? AND bed=?");
            pst.setString(1,"Not Booked");
            pst.setString(2, comboroomtype.getItemAt(comboroomtype.getSelectedIndex()));
            pst.setString(3, combobed.getItemAt(combobed.getSelectedIndex()));
            rs=pst.executeQuery();
            comboroomnumber.removeAllItems();
            while(rs.next()){
                comboroomnumber.addItem(rs.getString("roomnumber"));
            }
            pst=con.prepareStatement("select price from room where roomnumber=?");
            pst.setString(1,comboroomnumber.getItemAt(comboroomnumber.getSelectedIndex()));
            rs=pst.executeQuery();
            if(rs.next())
            txtprice.setText(rs.getString("price"));
        }catch(ClassNotFoundException | SQLException e){
        }
        
    }//GEN-LAST:event_comboroomtypeItemStateChanged

    private void comboroomtypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboroomtypeMouseClicked
    }//GEN-LAST:event_comboroomtypeMouseClicked

    private void comboroomtypeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboroomtypeMouseReleased
     // TODO add your handling code here:
    }//GEN-LAST:event_comboroomtypeMouseReleased

    private void combobedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combobedItemStateChanged
         PreparedStatement pst;
        ResultSet rs;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","ketan9535");
            pst=con.prepareStatement("select roomnumber from room where status=? AND roomtype=? AND bed=?");
            pst.setString(1,"Not Booked");
            pst.setString(2, comboroomtype.getItemAt(comboroomtype.getSelectedIndex()));
            pst.setString(3, combobed.getItemAt(combobed.getSelectedIndex()));
            rs=pst.executeQuery();
            comboroomnumber.removeAllItems();
            while(rs.next()){
                comboroomnumber.addItem(rs.getString("roomnumber"));
            }
            pst=con.prepareStatement("select price from room where roomnumber=?");
            pst.setString(1,comboroomnumber.getItemAt(comboroomnumber.getSelectedIndex()));
            rs=pst.executeQuery();
            if(rs.next())
            txtprice.setText(rs.getString("price"));
        }catch(ClassNotFoundException | SQLException e){
        }
        
    }//GEN-LAST:event_combobedItemStateChanged

    private void txtnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusGained

    }//GEN-LAST:event_txtnameFocusGained

    private void txtmobFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmobFocusLost
       // TODO add your handling code here:
    }//GEN-LAST:event_txtmobFocusLost

    private void txtemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusLost
     // TODO add your handling code here:
    }//GEN-LAST:event_txtemailFocusLost

    private void combogenderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combogenderFocusLost
     // TODO add your handling code here:
    }//GEN-LAST:event_combogenderFocusLost

    private void txtnatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnatFocusLost
      // TODO add your handling code here:
    }//GEN-LAST:event_txtnatFocusLost

    private void txtnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusLost
    }//GEN-LAST:event_txtnameFocusLost

    private void combogenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combogenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combogenderActionPerformed

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER)
    txtmob.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtmobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmobKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER)
    txtemail.requestFocus(); // TODO add your handling code here:
    }//GEN-LAST:event_txtmobKeyPressed

    private void txtemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER)
    combogender.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailKeyPressed

    private void combogenderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combogenderKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER)
   txtnat.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_combogenderKeyPressed

    private void txtnatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnatKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER)
    txtid.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtnatKeyPressed

    private void txtemailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailKeyTyped

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
     txtemail.setText(txtemail.getText().toLowerCase()); 

     int a=txtemail.getText().indexOf('@');
     int b=txtemail.getText().length();
      if(a == -1){
          lblemail.setText("Invalid Email id");
      }
      else if (b>a+1){
      String s=txtemail.getText();
      String[] splitString = s.split("@");
      if(splitString[1].equalsIgnoreCase("gmail.com")){
      lblemail.setText("");
      }
      else
         lblemail.setText(" Invalid Email id");
      }  
      if(txtemail.getText().equals(""))
          lblemail.setText("");      
    }//GEN-LAST:event_txtemailKeyReleased

    private void txtaddress1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtaddress1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddress1FocusLost

    private void txtaddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddress1ActionPerformed

    private void txtaddress1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaddress1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddress1KeyPressed

    private void txtidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        txtid.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtidKeyPressed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidFocusLost

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtmobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmobActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtnatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnatActionPerformed

    private void combobedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobedActionPerformed

    private void comboroomnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboroomnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboroomnumberActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CustomerCheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combobed;
    private javax.swing.JComboBox<String> combogender;
    private javax.swing.JComboBox<String> comboroomnumber;
    private javax.swing.JComboBox<String> comboroomtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblemail;
    private javax.swing.JTextField txtaddress1;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmob;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnat;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
